"""Generate C++ headers from mapping/ YAML files.

Generates two files:
  tsf/generated/mapping_table.h  — Korean syllable -> kana lookup table
  tsf/generated/batchim_rules.h  — Batchim (final consonant) rule tables

Run: python tsf/tools/gen_table.py
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

import yaml

# ---------------------------------------------------------------------------
# mapping_table.h
# ---------------------------------------------------------------------------

MAPPING_HEADER = """\
// AUTO-GENERATED by tsf/tools/gen_table.py — do not edit manually
// Re-generate: python tsf/tools/gen_table.py
#pragma once
#include <cwchar>
#include <cstddef>
#include <string>

namespace mapping {

struct Entry { const wchar_t* key; const wchar_t* val; };

// Sorted by key (wchar_t lexicographic order) for binary search
static constexpr Entry kTable[] = {
"""

MAPPING_FOOTER = """\
};
static constexpr std::size_t kTableSize = sizeof(kTable) / sizeof(kTable[0]);

// Returns kana string for a given Korean syllable, or empty string if not found
inline std::wstring lookup(const std::wstring& key) {
    const wchar_t* k = key.c_str();
    std::size_t lo = 0, hi = kTableSize;
    while (lo < hi) {
        std::size_t mid = lo + (hi - lo) / 2;
        int cmp = ::wcscmp(kTable[mid].key, k);
        if (cmp == 0) return kTable[mid].val;
        if (cmp < 0) lo = mid + 1;
        else hi = mid;
    }
    return {};
}

// Kept for compatibility — returns nullptr or val
inline const wchar_t* lookup_raw(const wchar_t* key) {
    std::size_t lo = 0, hi = kTableSize;
    while (lo < hi) {
        std::size_t mid = lo + (hi - lo) / 2;
        int cmp = ::wcscmp(kTable[mid].key, key);
        if (cmp == 0) return kTable[mid].val;
        if (cmp < 0) lo = mid + 1;
        else hi = mid;
    }
    return nullptr;
}

} // namespace mapping
"""

# ---------------------------------------------------------------------------
# batchim_rules.h
# ---------------------------------------------------------------------------

BATCHIM_HEADER = """\
// AUTO-GENERATED by tsf/tools/gen_table.py — do not edit manually
// Re-generate: python tsf/tools/gen_table.py
#pragma once
#include <string>

// Batchim (final consonant) rule tables derived from mapping/batchim.yaml.
// All jamo are Korean compatibility jamo (U+3131..U+3163).
namespace batchim_rules {

"""

BATCHIM_FOOTER = """\
} // namespace batchim_rules
"""


def escape_wstr(s: str) -> str:
    """Convert string to C++ L"..." literal body (no surrounding quotes)."""
    parts = []
    for ch in s:
        cp = ord(ch)
        if cp > 0xFFFF:
            parts.append(f"\\U{cp:08X}")
        elif cp > 0x7F:
            parts.append(f"\\u{cp:04X}")
        elif ch == '"':
            parts.append('\\"')
        elif ch == "\\":
            parts.append("\\\\")
        else:
            parts.append(ch)
    return "".join(parts)


def wlit(s: str) -> str:
    """Wrap a string as a C++ L"..." wide string literal (const wchar_t*)."""
    return f'L"{escape_wstr(s)}"'


def wclit(ch: str) -> str:
    """Wrap a single character as a C++ L'...' wide character literal (wchar_t)."""
    assert len(ch) == 1, f"wclit expects a single character, got: {ch!r}"
    return f"L'{escape_wstr(ch)}'"


# ---------------------------------------------------------------------------
# Batchim header generation
# ---------------------------------------------------------------------------

def _gen_bool_set(fn_name: str, items: list[str]) -> str:
    """Generate an inline bool function that checks membership in a jamo set."""
    literals = ", ".join(wclit(j) for j in items)
    return (
        f"inline bool {fn_name}(wchar_t jong) {{\n"
        f"    static const wchar_t kSet[] = {{ {literals} }};\n"
        f"    for (auto j : kSet) if (j == jong) return true;\n"
        f"    return false;\n"
        f"}}\n\n"
    )


def _gen_strict_fn(strict_map: dict[str, list[str]]) -> str:
    """Generate is_sokuon_strict(jong, next_initial) from the strict map."""
    lines = ["inline bool is_sokuon_strict(wchar_t jong, wchar_t next_initial) {\n"]

    # One null-terminated wchar_t array per jong entry (trigger consonants)
    array_decls = []
    table_entries = []
    for jong, triggers in strict_map.items():
        arr_name = f"kTrig_{ord(jong):04X}"
        lits = ", ".join(wclit(t) for t in triggers)
        array_decls.append(f"    static const wchar_t {arr_name}[] = {{ {lits}, 0 }};\n")
        table_entries.append(f"        {{ {wclit(jong)}, {arr_name} }},\n")

    lines += array_decls
    lines += [
        "    struct Entry { wchar_t jong; const wchar_t* triggers; };\n",
        "    static const Entry kTable[] = {\n",
    ]
    lines += table_entries
    lines += [
        "    };\n",
        "    for (const auto& e : kTable) {\n",
        "        if (e.jong != jong) continue;\n",
        "        for (const wchar_t* p = e.triggers; *p; ++p)\n",
        "            if (*p == next_initial) return true;\n",
        "        return false;\n",
        "    }\n",
        "    return false;\n",
        "}\n\n",
    ]
    return "".join(lines)


def _gen_foreign_fn(foreign_map: dict[str, str]) -> str:
    """Generate foreign_kana(jong) returning the fallback kana string."""
    lines = ["inline std::wstring foreign_kana(wchar_t jong) {\n"]
    lines += ["    struct Entry { wchar_t jong; const wchar_t* kana; };\n"]
    lines += ["    static const Entry kTable[] = {\n"]
    for jong, kana in foreign_map.items():
        # jong is a single jamo character → wchar_t literal
        # kana is a kana string → const wchar_t* literal
        lines.append(f"        {{ {wclit(jong)}, {wlit(kana)} }},\n")
    lines += [
        "    };\n",
        "    for (const auto& e : kTable)\n",
        "        if (e.jong == jong) return e.kana;\n",
        "    return L\"\";\n",
        "}\n\n",
    ]
    return "".join(lines)


def gen_batchim_header(rules: dict) -> str:
    parts = [BATCHIM_HEADER]

    parts.append(_gen_bool_set("is_hatsuon",          rules["hatsuon"]))
    parts.append(_gen_bool_set("is_sokuon_always",     rules["sokuon_always"]))
    parts.append(_gen_bool_set("is_sokuon_universal",  rules["sokuon_universal_markers"]))
    parts.append(_gen_bool_set("is_sokuon_terminal",   rules["sokuon_terminal"]))
    parts.append(_gen_strict_fn(rules["sokuon_strict"]))
    parts.append(_gen_foreign_fn(rules["foreign_batchim"]))

    parts.append(BATCHIM_FOOTER)
    return "".join(parts)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    syllables_path = ROOT / "mapping" / "syllables.yaml"
    batchim_path   = ROOT / "mapping" / "batchim.yaml"
    out_dir        = ROOT / "tsf" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    # --- mapping_table.h ---
    syllables: dict[str, str] = yaml.safe_load(
        syllables_path.read_text(encoding="utf-8")
    )
    mapping_lines = [MAPPING_HEADER]
    # Sort by Korean key Unicode codepoint order (matches wcscmp ordering)
    for kor, kana in sorted(syllables.items()):
        mapping_lines.append(f'    {{{wlit(kor)}, {wlit(kana)}}},\n')
    mapping_lines.append(MAPPING_FOOTER)

    mapping_out = out_dir / "mapping_table.h"
    mapping_out.write_text("".join(mapping_lines), encoding="utf-8")
    print(f"Generated {mapping_out} ({len(syllables)} entries)")

    # --- batchim_rules.h ---
    batchim_rules: dict = yaml.safe_load(
        batchim_path.read_text(encoding="utf-8")
    )
    batchim_content = gen_batchim_header(batchim_rules)

    batchim_out = out_dir / "batchim_rules.h"
    batchim_out.write_text(batchim_content, encoding="utf-8")
    print(f"Generated {batchim_out}")


if __name__ == "__main__":
    main()
